# Generated by Anaconda 34.25.4.9
# Generated by pykickstart v3.32
#version=RHEL9
# Use text mode install
text
repo --name="AppStream" --baseurl=http://x.x.x.x/rhel/9.5/AppStream
repo --name="BaseOS" --baseurl=http://x.x.x.x/rhel/9.5/BaseOS

%addon com_redhat_kdump --disable

%end

# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=enp1s0 --activate
network  --hostname=newhost.example.com

# Use network installation
url --url="http://x.x.x.x/rhel/9.5/"

%packages
@^minimal-environment
@standard

%end

# Run the Setup Agent on first boot
firstboot --disable
# Do not configure the X Window System
skipx

# Generated using Blivet version 3.6.0
ignoredisk --only-use=vda
# System bootloader configuration
bootloader --location=mbr --boot-drive=vda
autopart --type=plain
# Partition clearing information
clearpart --all --initlabel --drives=vda

# System timezone
timezone America/Denver --utc

# Root password
#rootpw --allow-ssh --iscrypted  xxxxxxx
#user --groups=wheel --name=serveradmin --password=xxxx --iscrypted --gecos="Server Administrator"
rootpw --plaintext password6789
user --groups=wheel --name=serveradmin --plaintext --password=password1234 --gecos="Server Administrator"

reboot
